package model

import (
	"fmt"

	owlGin "github.com/Cepave/open-falcon-backend/common/gin"
	ojson "github.com/Cepave/open-falcon-backend/common/json"
	"github.com/gin-gonic/gin"
)

type NqmAgentHeartbeatRequest struct {
	// The connection id of the NQM agent
	ConnectionId string `json:"connection_id" binding:"required"`
	// The hostname of the machine running NQM agent
	Hostname string `json:"hostname" binding:"required"`
	// The IP address of the NQM agent. It supports both IPv4 and IPv6 format
	IpAddress ojson.IP `json:"ip_address" binding:"required"`
	// The timestamp generated by hbs
	Timestamp ojson.JsonTime `json:"timestamp" binding:"required"`
}

func (r *NqmAgentHeartbeatRequest) Bind(c *gin.Context) {
	owlGin.BindJson(c, r)
}

func (r NqmAgentHeartbeatRequest) String() string {
	return fmt.Sprintf(
		"NqmAgentHeartbeatRequest{ConnectionId=%v Hostname=%v IpAddress=%v Timestamp=%v}",
		r.ConnectionId, r.Hostname, r.IpAddress, r.Timestamp,
	)
}
