package model

import (
	owlGin "github.com/Cepave/open-falcon-backend/common/gin"
	ojson "github.com/Cepave/open-falcon-backend/common/json"
	"github.com/gin-gonic/gin"
)

type FalconAgentHeartbeat struct {
	Hostname      string `json:"hostname" conform:"trim"`
	IP            string `json:"ip" conform:"trim"`
	AgentVersion  string `json:"agent_version" conform:"trim"`
	PluginVersion string `json:"plugin_version" conform:"trim"`
	UpdateTime    int64  `json:"update_time" conform:"trim"`
}

type FalconAgentHeartbeatResult struct {
	RowsAffected int64 `json:"rows_affected"`
}

type NqmAgentHeartbeatRequest struct {
	// The connection id of the NQM agent
	ConnectionId string `json:"connection_id"`
	// The hostname of the machine running NQM agent
	Hostname string `json:"hostname"`
	// The IP address of the NQM agent. It supports both IPv4 and IPv6 format
	IpAddress ojson.IP `json:"ip_address"`
	// The timestamp generated by hbs
	Timestamp ojson.JsonTime `json:"timestamp"`
}

func (r *NqmAgentHeartbeatRequest) Bind(c *gin.Context) {
	owlGin.BindJson(c, r)
}
