// Code generated by protoc-gen-go.
// source: proto/owlquery/grafana.proto
// DO NOT EDIT!

/*
Package grafana is a generated protocol buffer package.

It is generated from these files:
	proto/owlquery/grafana.proto

It has these top-level messages:
	QueryInput
	QueryReply
*/
package grafana

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// query string that will send to server
type QueryInput struct {
	StartTs   int32  `protobuf:"varint,1,opt,name=start_ts" json:"start_ts,omitempty"`
	EndTs     int32  `protobuf:"varint,2,opt,name=end_ts" json:"end_ts,omitempty"`
	Consolfun string `protobuf:"bytes,3,opt,name=consolfun" json:"consolfun,omitempty"`
	Endpoint  string `protobuf:"bytes,4,opt,name=endpoint" json:"endpoint,omitempty"`
	Counter   string `protobuf:"bytes,5,opt,name=counter" json:"counter,omitempty"`
}

func (m *QueryInput) Reset()                    { *m = QueryInput{} }
func (m *QueryInput) String() string            { return proto.CompactTextString(m) }
func (*QueryInput) ProtoMessage()               {}
func (*QueryInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The response message from server
type QueryReply struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *QueryReply) Reset()                    { *m = QueryReply{} }
func (m *QueryReply) String() string            { return proto.CompactTextString(m) }
func (*QueryReply) ProtoMessage()               {}
func (*QueryReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*QueryInput)(nil), "grafana.QueryInput")
	proto.RegisterType((*QueryReply)(nil), "grafana.QueryReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for OwlQuery service

type OwlQueryClient interface {
	// Sends a query to server
	Query(ctx context.Context, in *QueryInput, opts ...grpc.CallOption) (*QueryReply, error)
}

type owlQueryClient struct {
	cc *grpc.ClientConn
}

func NewOwlQueryClient(cc *grpc.ClientConn) OwlQueryClient {
	return &owlQueryClient{cc}
}

func (c *owlQueryClient) Query(ctx context.Context, in *QueryInput, opts ...grpc.CallOption) (*QueryReply, error) {
	out := new(QueryReply)
	err := grpc.Invoke(ctx, "/grafana.OwlQuery/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OwlQuery service

type OwlQueryServer interface {
	// Sends a query to server
	Query(context.Context, *QueryInput) (*QueryReply, error)
}

func RegisterOwlQueryServer(s *grpc.Server, srv OwlQueryServer) {
	s.RegisterService(&_OwlQuery_serviceDesc, srv)
}

func _OwlQuery_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(QueryInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(OwlQueryServer).Query(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _OwlQuery_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grafana.OwlQuery",
	HandlerType: (*OwlQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _OwlQuery_Query_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4a, 0xc5, 0x30,
	0x10, 0x85, 0xad, 0x9a, 0xfe, 0xcc, 0x32, 0xa2, 0xc4, 0xcb, 0x5d, 0x48, 0x71, 0xe1, 0xea, 0x5e,
	0xb0, 0x0f, 0xe0, 0xda, 0x95, 0x18, 0xdc, 0x4b, 0xac, 0xa9, 0x08, 0x21, 0x89, 0xc9, 0x84, 0xd2,
	0xd7, 0xf0, 0x89, 0x4d, 0xc7, 0xd6, 0x82, 0xbb, 0x7c, 0xe7, 0x3b, 0x84, 0x99, 0x81, 0xbd, 0x0f,
	0x0e, 0xdd, 0xd1, 0x8d, 0xe6, 0x2b, 0xe9, 0x30, 0x1d, 0x3f, 0x82, 0x1a, 0x94, 0x55, 0x07, 0x8a,
	0x79, 0xb5, 0x60, 0xfb, 0x5d, 0x00, 0x3c, 0xcf, 0x85, 0x47, 0xeb, 0x13, 0xf2, 0x6b, 0xa8, 0x23,
	0xaa, 0x80, 0xaf, 0x18, 0x45, 0x71, 0x53, 0xdc, 0x31, 0x59, 0x11, 0xbf, 0x44, 0x7e, 0x09, 0xa5,
	0xb6, 0xef, 0xb3, 0x38, 0x25, 0xc1, 0x32, 0xe5, 0x78, 0x0f, 0x4d, 0xef, 0x6c, 0x74, 0x66, 0x48,
	0x56, 0x9c, 0x65, 0xd3, 0xc8, 0x2d, 0xe0, 0x3b, 0xa8, 0x73, 0xcd, 0xbb, 0x4f, 0x8b, 0xe2, 0x9c,
	0xe4, 0x1f, 0x73, 0x01, 0x55, 0xef, 0x92, 0x45, 0x1d, 0x04, 0x23, 0xb5, 0x62, 0x7b, 0xbb, 0xcc,
	0x24, 0xb5, 0x37, 0x13, 0xbf, 0x82, 0x32, 0xe8, 0x98, 0x0c, 0xd2, 0x44, 0x8d, 0x5c, 0xe8, 0xfe,
	0x01, 0xea, 0xa7, 0xd1, 0x50, 0x91, 0x77, 0xc0, 0x7e, 0x1f, 0x17, 0x87, 0x75, 0xd1, 0x6d, 0xab,
	0xdd, 0xbf, 0x90, 0xbe, 0x6d, 0x4f, 0xde, 0x4a, 0xba, 0x45, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x5a, 0x49, 0xcd, 0xb0, 0x2b, 0x01, 0x00, 0x00,
}
