ALTER TABLE city CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE idc CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE province CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
